sudo: false
language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
env:
  - ACTIVERECORD=2.3.8
  - ACTIVERECORD=3.0.0
  - ACTIVERECORD=3.1.0
  - ACTIVERECORD=3.2.0
  - ACTIVERECORD=4.0.0
matrix:
  exclude:
    - rvm: 1.8.7
      env: ACTIVERECORD=4.0.0
    - rvm: 1.9.3
      env: ACTIVERECORD=2.3.8
    - rvm: 2.0.0
      env: ACTIVERECORD=2.3.8
    - rvm: 2.0.0
      env: ACTIVERECORD=3.0.0
    - rvm: 2.0.0
      env: ACTIVERECORD=3.1.0
addons:
  code_climate:
    repo_token: a90435ed4954dd6e9f3697a20c5bc3754f67d94703f870e8fc7b00f69f5b2d06
