language: ruby
dist: focal
os: linux
cache: bundler
rvm:
  - 2.6.10
  - 2.7.6
env:
  - ACTIVERECORD=5.1.1
  - ACTIVERECORD=5.2.8
  - ACTIVERECORD=6.0.6
  - ACTIVERECORD=6.1.7
  - ACTIVERECORD=7.0.4
jobs:
  fast_finish: false
  exclude:
    - rvm: 2.6.10
      env: ACTIVERECORD=7.0.4

addons:
  code_climate:
    repo_token: a90435ed4954dd6e9f3697a20c5bc3754f67d94703f870e8fc7b00f69f5b2d06
